//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDF_DATA.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GDF_DATA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Level,레벨
        ///ReqExp,요구 경험치
        ///MaxHP,최대 체력
        ///MaxMana,최대 마나
        ///PhysicalAttack,물리 공격력
        ///MagicAttack,술법 공격력
        ///PhysicalDefense,물리 방어력
        ///MagicDefense,술법 방어력
        ///Accuracy,명중
        ///Dodge,회피
        ///Critical,치명
        ///AvoidCritical,치명회피
        ///CriticalOutcome,치명피해
        ///ReducePhysicalDef,물리 방어 무시
        ///ReduceMagicDef,술법 방어 무시
        ///Luck,행운
        ///ManaCost,마력소모
        ///ActingPointMax,최대 행동력
        ///RecommendCombatpoint,권장 전투력
        ///SlotNumber,체질 대상 슬롯
        ///MasteryCount,체질 레벨
        ///MasteryItemUseId1,필요 재료 #1
        ///MasteryItemUseId1Count,체질 재료 1 개수
        ///MasteryItemUseId2,필요 재료 #2
        ///MasteryItemUseId2Count,체질 재료 2 개[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ColumnNameList {
            get {
                return ResourceManager.GetString("ColumnNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CheatItemSet_Table
        ///CINEMATIC_DIALOGUE
        ///CUSTOMIZING_TYPE
        ///LOADING
        ///MAIL_PRESET
        ///SLANG_CHATTING
        ///능력치 속성 정의.xlsx
        ///템플릿 자동 서식
        ///템플릿 자동 서식_GenData용
        ///템플릿 자동 서식_GENDOOR용
        ///템플릿 자동 서식_표형식
        ///복사본
        ///GUILD_CONTRIBUTION_GRADE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ignoreExcel {
            get {
                return ResourceManager.GetString("ignoreExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gen,json_gendata
        ///ITEM_GETWAY,json_item_getway
        ///Npc,json_npc
        ///Waypoint,json_Waypoint
        ///Trigger_GroupBase,json_Trigger_GroupBase
        ///MapMini,json_MapMini
        ///SafetyArea,json_SafetyArea
        ///SectorGrade,json_SectorGrade
        ///DungeonScript,json_DungeonScript과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string JsonConvert {
            get {
                return ResourceManager.GetString("JsonConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] ProgramSettingData {
            get {
                object obj = ResourceManager.GetObject("ProgramSettingData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   UI_SHOP_GOODS.json,rowid
        ///PLAYDATA.json,PlayDataId
        ///GACHA_GROUP.json,Name:GroupId과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StandardColumn {
            get {
                return ResourceManager.GetString("StandardColumn", resourceCulture);
            }
        }
    }
}
